import type { Business, Notification } from "@/types";

export const MOCK_USER = {
  id: "user_1",
  name: "Alex Johnson",
  email: "alex@example.com",
  role: "both" as const,
  verified: true,
  createdAt: new Date("2024-01-15"),
};

export const MOCK_BUSINESSES: Business[] = [
  {
    id: "biz_1",
    title: "SaaS Project Management Tool",
    slug: "saas-project-management-tool",
    description: "Profitable B2B SaaS platform with 1,200 paying customers. 94% retention rate, strong MRR growth, minimal churn. Built on React + Node.js with a clean codebase and automated operations.",
    type: "saas",
    status: "active",
    industry: "Technology",
    location: "Remote / US",
    askingPrice: 2_400_000,
    revenue: 800_000,
    ebitda: 480_000,
    sde: 520_000,
    multiple: 3.0,
    yearEstablished: 2020,
    employees: 4,
    seller: { id: "seller_1", name: "Sarah Chen", email: "sarah@ex.com", role: "seller", verified: true, createdAt: new Date() },
    images: [],
    highlights: ["94% customer retention", "1,200 active users", "Automated ops", "$67K MRR"],
    tags: ["saas", "b2b", "remote", "recurring-revenue"],
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15"),
    viewCount: 847,
  },
  {
    id: "biz_2",
    title: "E-commerce Outdoor Gear Brand",
    slug: "ecommerce-outdoor-gear-brand",
    description: "DTC outdoor equipment brand with strong Amazon and Shopify presence. Established supplier relationships, 40K email subscribers, and seasonal revenue peak in Q2/Q4.",
    type: "ecommerce",
    status: "active",
    industry: "Retail / Outdoor",
    location: "Denver, CO",
    askingPrice: 1_750_000,
    revenue: 2_100_000,
    ebitda: 315_000,
    sde: 380_000,
    multiple: 4.6,
    yearEstablished: 2018,
    employees: 3,
    seller: { id: "seller_2", name: "Mark Williams", email: "mark@ex.com", role: "seller", verified: true, createdAt: new Date() },
    images: [],
    highlights: ["40K email list", "Amazon + Shopify", "Established brand", "Supplier contracts"],
    tags: ["ecommerce", "dtc", "amazon", "outdoor"],
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-03-10"),
    viewCount: 1203,
  },
  {
    id: "biz_3",
    title: "Digital Marketing Agency",
    slug: "digital-marketing-agency",
    description: "Full-service digital marketing agency specializing in SEO and paid ads for healthcare clients. Recurring retainer model, 18 long-term clients, lean team of 6.",
    type: "service",
    status: "active",
    industry: "Marketing / Healthcare",
    location: "Austin, TX",
    askingPrice: 920_000,
    revenue: 1_100_000,
    ebitda: 275_000,
    sde: 310_000,
    multiple: 2.97,
    yearEstablished: 2017,
    employees: 6,
    seller: { id: "seller_3", name: "Jennifer Park", email: "jen@ex.com", role: "seller", verified: true, createdAt: new Date() },
    images: [],
    highlights: ["18 retainer clients", "Healthcare niche", "Recurring revenue", "6-year track record"],
    tags: ["agency", "seo", "healthcare", "retainer"],
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-03-18"),
    viewCount: 562,
  },
  {
    id: "biz_4",
    title: "Content Creator Network",
    slug: "content-creator-network",
    description: "YouTube + newsletter empire with 2.1M combined subscribers in the personal finance niche. Monetized via ads, sponsorships, and digital products. 80%+ margins.",
    type: "content",
    status: "active",
    industry: "Media / Finance",
    location: "Remote",
    askingPrice: 3_200_000,
    revenue: 960_000,
    ebitda: 768_000,
    sde: 820_000,
    multiple: 3.9,
    yearEstablished: 2019,
    employees: 2,
    seller: { id: "seller_4", name: "David Torres", email: "david@ex.com", role: "seller", verified: true, createdAt: new Date() },
    images: [],
    highlights: ["2.1M subscribers", "80%+ margins", "Multiple revenue streams", "Fully systemized"],
    tags: ["content", "youtube", "newsletter", "finance"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-03-12"),
    viewCount: 2941,
    isSaved: true,
  },
  {
    id: "biz_5",
    title: "Brick & Mortar Gym Franchise",
    slug: "brick-mortar-gym-franchise",
    description: "Profitable fitness center with 850 active members in a prime suburban location. 5-year lease, modern equipment, and a loyal member base with automated billing.",
    type: "brick-and-mortar",
    status: "active",
    industry: "Fitness / Health",
    location: "Chicago, IL",
    askingPrice: 680_000,
    revenue: 720_000,
    ebitda: 180_000,
    sde: 220_000,
    multiple: 3.1,
    yearEstablished: 2016,
    employees: 8,
    seller: { id: "seller_5", name: "Lisa Morgan", email: "lisa@ex.com", role: "seller", verified: true, createdAt: new Date() },
    images: [],
    highlights: ["850 active members", "Prime location", "Modern equipment", "5-year lease"],
    tags: ["gym", "fitness", "franchise", "membership"],
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-03-14"),
    viewCount: 389,
  },
  {
    id: "biz_6",
    title: "B2B SaaS HR Platform",
    slug: "b2b-saas-hr-platform",
    description: "Mid-market HR software serving 85 enterprise clients. HRIS, payroll, and performance management modules. Strong NPS of 72, ISO 27001 certified.",
    type: "saas",
    status: "active",
    industry: "Technology / HR",
    location: "New York, NY",
    askingPrice: 8_500_000,
    revenue: 2_200_000,
    ebitda: 990_000,
    sde: 1_050_000,
    multiple: 8.1,
    yearEstablished: 2015,
    employees: 18,
    seller: { id: "seller_6", name: "Robert Kim", email: "rob@ex.com", role: "seller", verified: true, createdAt: new Date() },
    images: [],
    highlights: ["85 enterprise clients", "NPS: 72", "ISO 27001 certified", "HRIS + Payroll"],
    tags: ["saas", "hr", "enterprise", "b2b"],
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-03-08"),
    viewCount: 1876,
    isSaved: true,
  },
  {
    id: "biz_7",
    title: "Amazon FBA Portfolio",
    slug: "amazon-fba-portfolio",
    description: "Bundle of 3 private-label Amazon FBA brands in home goods. Combined 4.6-star rating, 15K+ reviews, seasonal-resilient, and fully VA-managed.",
    type: "ecommerce",
    status: "under-offer",
    industry: "E-commerce / Home",
    location: "Remote",
    askingPrice: 1_100_000,
    revenue: 1_450_000,
    ebitda: 290_000,
    sde: 320_000,
    multiple: 3.44,
    yearEstablished: 2021,
    employees: 1,
    seller: { id: "seller_7", name: "Emily Rodriguez", email: "emily@ex.com", role: "seller", verified: true, createdAt: new Date() },
    images: [],
    highlights: ["3 brand portfolio", "15K+ reviews", "4.6★ avg rating", "VA-managed"],
    tags: ["amazon", "fba", "private-label", "home-goods"],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-03-17"),
    viewCount: 2104,
  },
  {
    id: "biz_8",
    title: "Marketplace Platform – Freelancers",
    slug: "marketplace-platform-freelancers",
    description: "Two-sided marketplace connecting freelance developers with SMBs. 8K registered users, 12% take rate, growing 15% MoM. Fully automated escrow and dispute resolution.",
    type: "marketplace",
    status: "active",
    industry: "Technology / Gig Economy",
    location: "Remote",
    askingPrice: 1_850_000,
    revenue: 620_000,
    ebitda: 248_000,
    sde: 280_000,
    multiple: 6.6,
    yearEstablished: 2022,
    employees: 2,
    seller: { id: "seller_8", name: "Chris Lee", email: "chris@ex.com", role: "seller", verified: true, createdAt: new Date() },
    images: [],
    highlights: ["8K users", "15% MoM growth", "12% take rate", "Automated escrow"],
    tags: ["marketplace", "saas", "freelance", "two-sided"],
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-19"),
    viewCount: 743,
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: "n1", userId: "user_1", type: "offer", title: "New Offer Received", body: "You received a $2.1M offer on SaaS Project Management Tool", read: false, link: "/dashboard", createdAt: new Date(Date.now() - 3600000) },
  { id: "n2", userId: "user_1", type: "escrow", title: "Escrow Milestone Reached", body: "Due diligence deposit of $50K has been received", read: false, link: "/escrow", createdAt: new Date(Date.now() - 7200000) },
  { id: "n3", userId: "user_1", type: "message", title: "New Message from Sarah Chen", body: "Can you share the last 3 years of P&L statements?", read: true, link: "/dashboard/messages", createdAt: new Date(Date.now() - 86400000) },
  { id: "n4", userId: "user_1", type: "document", title: "NDA Ready to Sign", body: "The NDA for Content Creator Network is ready for your signature", read: true, link: "/dashboard", createdAt: new Date(Date.now() - 172800000) },
];

export const REVENUE_DATA = [
  { month: "Apr", revenue: 58000, expenses: 32000 },
  { month: "May", revenue: 62000, expenses: 34000 },
  { month: "Jun", revenue: 71000, expenses: 36000 },
  { month: "Jul", revenue: 68000, expenses: 35000 },
  { month: "Aug", revenue: 75000, expenses: 37000 },
  { month: "Sep", revenue: 82000, expenses: 39000 },
  { month: "Oct", revenue: 78000, expenses: 38000 },
  { month: "Nov", revenue: 88000, expenses: 41000 },
  { month: "Dec", revenue: 95000, expenses: 43000 },
  { month: "Jan", revenue: 91000, expenses: 42000 },
  { month: "Feb", revenue: 98000, expenses: 44000 },
  { month: "Mar", revenue: 105000, expenses: 46000 },
];

export const TESTIMONIALS = [
  { id: "t1", name: "Michael Torres", role: "Sold a SaaS for $4.2M", avatar: "MT", quote: "Explorify gave me access to 200+ qualified buyers in the first week. The escrow system made me feel secure every step of the way. Closed in 62 days.", rating: 5 },
  { id: "t2", name: "Amanda Chase", role: "Acquired 3 Businesses via Explorify", avatar: "AC", quote: "The financial modeling tools are incredible. I can stress-test any acquisition in minutes and compare opportunities side-by-side. The team support is world-class.", rating: 5 },
  { id: "t3", name: "James Nakamura", role: "E-commerce Exit – $1.8M", avatar: "JN", quote: "From listing to close in 45 days. The platform handles everything – NDA signing, document sharing, escrow milestones. I'll never use a broker again.", rating: 5 },
];

export const STATS = [
  { label: "Businesses Sold", value: "2,400+", subtext: "Since 2022" },
  { label: "Total Deal Volume", value: "$1.2B+", subtext: "Across all transactions" },
  { label: "Avg. Days to Close", value: "54", subtext: "Vs. 6 months traditional" },
  { label: "Buyer Satisfaction", value: "98.2%", subtext: "From post-close surveys" },
];
